services:
  vietplatevision:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vietplatevision
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
      - ./model:/app/model
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: unless-stopped
